timezone: "America/New_York"
exclude: ["posts/*.md", "about/*.md", "commonmark_games/*.md"]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
title: "Sam's Fiction Workshop"
description: "Sam's Blog on all things fiction: Books, Movies, and RPGs."
source: [/]