timezone: "America/New_York"
exclude: [vendor]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
title: "Sam's Fiction Workshop"
description: "Sam's Blog on all things fiction: Books, Movies, and RPGs."
include: [/posts/]
source: [/]
defaults:
  - scope:
      path: "posts/*"
    values:
      layout: null
      type: "blog post"