import random as rand

rooms = [
    "lab equipment room",
    "cafeteria",
    "personal office",
    "hydroponic station",
    "meeting/conference room",
    "seed storage room",
    "kitchen",
    "lounge",
    "gym",
    "server room",
    "dormitory",
    "personal lockers",
    "germination room",
    "seed cryo chamber",
    "security room",
  "lecture halls",
  "utilities room",
  "walk-in freezer",
  "dissection lab",
  "soil storage",
    ]

plants = [
  "cactus",
  "orchid",
  "lichen",
  "mushroom",
  "venus fly trap",
  "water lily",
  "rose",
  "sunflower",
  "corn",
  "oak",
  "bushes/topiary",
  "kelp",
  "dandelion",
  "crabgrass",
  "kudzu",
  "sequoia",
  "tropical flower",
  "coffee",
  "pine",
  "marsh grass",
  "palm plant",
  "mangrove",
  "apple",
  "bamboo",
  "ivy",
  "vines",
  "tumbleweed",
  "pitcher plant",
  "wild grass",
  "edelweiss",
  "tea",
  "pinecone",
  "rice",
  "coconut",
  "acorn",
    ]

traps = [
    "acid pool",
    "adhesive",
    "alarm",
    "armor melts",
    "bear trap",
    "blinding spray",
    "lava flow",
    "lightning",
    "living statues",
    "missile fire",
    "monster",
    "net trap",
    "blunt pendulum",
    "boiling tar",
    "collapsing floor",
    "crodoile pit",
    "crushing walls",
    "deep pit",
    "pendulum blade",
    "poison gas",
    "poison needle",
    "quicksand",
    "rage gas",
    "rolling boulder",
    "falling cage",
    "falling ceiling",
    "fills with sand",
    "flooding",
    "giant magnet",
    "hard vacuum",
    "room freezes",
    "room on fire",
    "sleeping gas",
    "spiked pit",
    "tombs open",
    "wall spikes"
]

missions = [
    "apprehend",
    "assassinate",
    "blackmail",
    "burlge",
    "chart",
    "convince",
    "infiltrate",
    "infiltrate",
    "Interrogate",
    "investigate",
    "kidnap",
    "locate",
    "plant",
    "deface",
    "defraud",
    "deliver",
    "destroy",
    "discredit",
    "escort",
    "protect",
    "raid",
    "replace",
    "retrieve",
    "rob",
    "ruin",
    "exfiltrate",
    "extort",
    "follow",
    "frame",
    "impersonate",
    "impress",
    "sabotage",
    "smuggle",
    "surveil",
    "take over",
    "terrorize",
    "threaten"]

physeffect = [
    "animating",
    "attracting",
    "binding",
    "blossoming",
    "consuming",
    "creeping",
    "levitating",
    "opening",
    "petrifying",
    "phasing",
    "piercing",
    "pursuing",
    "crushing",
    "diminishing",
    "dividing",
    "duplicating",
    "eveloping",
    "expanding",
    "reflecting",
    "regenerating",
    "rending",
    "repelling",
    "resurrecting",
    "screaming",
    "fusing",
    "grasping",
    "hastening",
    "hindering",
    "illuminating",
    "imprisoning",
    "sealing",
    "shapeshifting",
    "shielding",
    "spawning",
    "transmuting",
    "transporting",
    ]

etheffect = [
    "avenging",
    "banishing",
    "bewildering",
    "blinding",
    "charming",
    "communicating",
    "excruciating",
    "forseeing",
    "intoxicating",
    "maddening",
    "mesmerizing",
    "mindreading",
    "compelling",
    "concealing",
    "deafening",
    "deceiving",
    "deciphering",
    "disguising",
    "nullifying",
    "paralyzing",
    "revealing",
    "revolting",
    "scrying",
    "silencing",
    "dispelling",
    "emboldening",
    "encoding",
    "energizing",
    "enlightening",
    "enraging",
    "soothing",
    "summoning",
    "terrifying",
    "warding",
    "wearying",
    "withering",
    ]

contents = [
    "stairs down",
    "trap",
    "trap",
    "trap",
    "trap",
    "monster",
    "monster",
    "monster",
    "monster",
    "trap and monster",
    "trap and monster",
    "seed capsule",
    "empty",
    "empty",
    "emtpy",
    "empty",
    "empty",
    "empty",
    "3d6 seeds",
    "6d4 seeds",
]

animals = [
    "ant",
    "ape",
    "armadillo",
    "badger",
    "bear",
    "boar",
    "mole",
    "ostrich",
    "ox",
    "porcupine",
    "rabbit",
    "raccoon",
    "caterpillar",
    "centipede",
    "chameleon",
    "cockroach",
    "deer",
    "elephant",
    "rat",
    "rhinoceros",
    "scorpion",
    "sheep",
    "slug",
    "snail",
    "ferret",
    "fox",
    "giraffe",
    "goat",
    "hose",
    "human",
    "snake",
    "spider",
    "squirrel",
    "tiger",
    "wolf",
    "wolverine",
    ]

ability = [
    "absorbing",
    "acid blood",
    "anti-magic",
    "blinding",
    "breath weapon",
    "camouflaging",
    "mimicking",
    "mind-reading",
    "paralyzing",
    "phasing",
    "physical effect",
    "poisonous",
    "duplicating",
    "electric",
    "entangling",
    "ethereal effect",
    "exploding",
    "flying",
    "radioactive",
    "reflective",
    "regenerative",
    "shapeshifting",
    "spell-casting",
    "stealthy",
    "gaze weapon",
    "hypnotizing",
    "impervious",
    "invisible",
    "life-draining",
    "magnetic",
    "strangling",
    "super-strength",
    "telekinetic",
    "teleporting",
    "vampiric",
    "wall-crawling"
    ]
    

def trap():
    trap = rand.choice(traps)
    if trap == "monster":
        content = monster()
    return "trap: " + trap

def monster():
    bio = rand.choice(plants)
    form = rand.choice(animals)
    return "monster: " + bio + " " + form + " with " + rand.choice(ability)

def make_room(num):
    for i in range(num):
        room_type = rand.choice(rooms)
        content = rand.choice(contents)
        if content == "trap":
            content = trap()
        if content == "monster":
            content = monster()
        if content == "trap and monster":
            content = trap() + " and " + monster()
            
        print("Room " + str(i) + ": " + "The " + room_type + " contains " + content + ". The room has " + rand.choice(plants) + " spliced with " + rand.choice(plants) + ".\n")


make_room(40)
